# Topic: Social movement/protests

More specifically: anti-ICE (Immigration and Customs Enforcement) protests in Minnesota and nation-wide

## Q1 (10 pts): Keyword selection

Write the keywords you selected and explain your reasoning behind selecting each of them.

1. **"anti-ICE"**: this is the key term for specifically pointing to the social movements and protests, the recent anti-ICE protests following incidents in Minnesota that quickly spread nation-wide, as compared to a more general keyword of "ice" which covers all issues like their operations as well as resistance. Might be more used in liberal sources.
2. **"ICE protest", "ICE rally"**: another way of finding relevant info on anti-ICE protests is by searching "ICE" and "protest" together, so I decided to include this as well as separately they can mean very broadly may include non-relevant news.
3. **"ICE Minneapolis"**: main city where ICE wreak havoc in recent news. When I'm scraping chronogically, news in Minnesota, especially Minneapolis mostly cover ICE operations and protests. When I scraped Minneapolis, some noises were included with content irrelevant to ICE protests, so I'm adding keyword of both "ICE" and "Minneapolis" together as filter.
4. **"ICE Minnesota"**: similar to Minneapolis, news also report the ICE operations and protests by referring the main movement site as the state of Minnesota instead of its capital city.
6. **"Renee Good"**: prominent victim of ICE shooting on protestor that sparked outrage and protests against ICE, this will be the most relevant keyword to look for in a video's title.
7. **"Alex Pretti"**: same reasoning as Renee Good.

**Extra note**: emphasis on matching keyword for "ICE" as it's not a great acronym and lower-cased "ice" is easy to be mismatched to irrelevent topics. I updated the code to process this specific keyword as a special case (as an acronym, it's primarily used in all capitals and no plural) so that it will only give a match if it's used in the title exactly as is ("ICE").

In [55]:
KEYWORDS = [("anti-ice",), ("ICE", "protest"), ("ICE", "minneapolis"), ("ICE", "minnesota"), 
            ("renee", "good"), ("alex", "pretti"), ("ICE", "rally")]

In [56]:
import re

# Function to process/check keyword against title/post texts:
def checkKeywords(texts):
    """
    Takes string of source texts. For each tuple in KEYWORDS list, it will iterate over each word and:
    - If word is "ICE", check if texts contain exact term "ICE"
    - Else, check if word is in texts (case-insensitive)
    
    Returns True if all words in tuple is in source texts, else returns False.
    """
    texts_lower = texts.lower()
    
    for kw_tuple in KEYWORDS:
        if all(re.search(r'\bICE\b', texts) if w == "ICE" else w.lower() in texts_lower for w in kw_tuple):
            return True
            
    return False

## Q2 (40 pts): YouTube data collection

**2a (15 pts)**: For each of the two YouTube channels (CNN and FoxNews) use the YouTube API
to list all the videos uploaded on the channel starting with the most recent. Then go over the
videos and check whether the video title contains any of the topic-related keywords you
selected in Q1. If it does, save relevant information about the video. Make sure that you have
identified at least 50 topic-related videos per channel (i.e., 100 videos in total).
HINT: When checking for keywords, make sure your search is not case-sensitive (e.g.,
“Election” vs. “election”). Similarly, singular and plural forms should be treated as matches when
appropriate (e.g., “election” and “elections”).

In [57]:
API_KEY = "AIzaSyC7UId8_7-DEFVRKNRW0mZI4Zw8fBdLgGU"

In [58]:
# Run this at each new login of Jupyterhub instance

!pip install --upgrade google-api-python-client --quiet

In [59]:
import json

import googleapiclient
import googleapiclient.discovery
import googleapiclient.errors

In [60]:
# Initialize Youtube API
youtube = googleapiclient.discovery.build("youtube", "v3", developerKey=API_KEY)

In [61]:
def getUploadsId(youtube, channel_id):
    request = youtube.channels().list(
        part="contentDetails",
        id=channel_id
    )
    res = request.execute()
    return res["items"][0]["contentDetails"]["relatedPlaylists"]["uploads"]

In [62]:
cnn_id = getUploadsId(youtube, "UCupvZG-5ko_eiXAupbDfxWw")
cnn_id

'UUupvZG-5ko_eiXAupbDfxWw'

In [63]:
import re

def getRelevantVideos(youtube, uploads_id):
    relevant_videos = []
    next_page_token = None
    
    #while len(relevant_videos) < count:
    while True: 
        request = youtube.playlistItems().list(
            part="snippet",
            playlistId=uploads_id,
            maxResults=50,
            pageToken = next_page_token
        )
        res = request.execute()
        
        for v in res["items"]:
            title = v["snippet"]["title"]            
            
            if checkKeywords(title):
                # Save relevant metadata
                video_id = v["snippet"]["resourceId"]["videoId"]
                video_date = v["snippet"]["publishedAt"]
                video_description = v["snippet"]["description"]

                # Save view count
                request = youtube.videos().list(
                    part="statistics",
                    id=video_id
                    )
                response = request.execute()
                view_count = response['items'][0]['statistics']['viewCount']
                
                temp_dict = {'video_id': video_id,
                             'view_count': view_count,
                            'title': title,
                            'video_date': video_date,
                            'video_description': video_description}
                relevant_videos.append(temp_dict)
                 
        next_page_token = res.get("nextPageToken")
        # Stop if there are no more pages
        if not next_page_token:
            break         

    return relevant_videos

In [64]:
cnn_videos = getRelevantVideos(youtube, cnn_id)

In [65]:
len(cnn_videos)

81

In [66]:
fox_id = getUploadsId(youtube, "UCXIJgqnII2ZOINSWNOGFThA")
fox_videos = getRelevantVideos(youtube, fox_id)

In [67]:
len(fox_videos)

291

**2b (15 pts)**: For each video fetch the 30 most relevant (as sorted by the API) comments. If the
video has fewer than 30 comments, extract as many comments as there are. Make sure this
does not happen very often; if it does, understand and explain why.

In [68]:
def getComments(youtube, video_id, max_count=30):
    comments_info = []
    
    request = youtube.commentThreads().list(
        videoId=video_id,
        part="id,snippet,replies",
        textFormat="plainText",
        order="relevance",
        maxResults=max_count
    )
    res = request.execute()

    for c in res["items"]:
        path = c["snippet"]["topLevelComment"]
        snippet = path["snippet"]
        temp_dict = {'video_id': video_id,
                     'comment_id': path["id"],
                     'comment_text': snippet["textOriginal"],
                     'comment_author_name': snippet["authorDisplayName"],
                     'comment_author_channel_id': snippet["authorChannelId"]["value"],
                     'comment_date': snippet["publishedAt"],
                     'comment_likes': snippet["likeCount"],
                     'comment_reply_count': c["snippet"]["totalReplyCount"]
        }
        comments_info.append(temp_dict)
    return comments_info

In [69]:
# CNN videos
cnn_comments = []

for i, video in enumerate(cnn_videos):
    video_id = video['video_id']
    comments = getComments(youtube, video_id)
    cnn_comments.extend(comments)

len(cnn_comments)  # All videos have at least 30 comments

2430

In [70]:
# Fox News videos
fox_comments = []

for i, video in enumerate(fox_videos):
    video_id = video['video_id']
    comments = getComments(youtube, video_id)
    fox_comments.extend(comments)

len(fox_comments)  # All videos have at least 30 comments

8722

**2c (8 pts)**: Create a Pandas data frame that contains the relevant information about the data
you extracted. Each row of your data frame should represent one comment. It should, at least,
include the following columns (you can name the columns as you like):
1. Channel name
2. Video id
3. Video title
4. Video creation time
5. Video number of views
6. Comment id
7. Comment title
8. Comment creation time
9. Comment number of likes

Make sure that you have at least 1000 rows per channel.
Print the number of rows in the data frame and display the first few rows of the data frame using
head().

In [71]:
import pandas as pd

cnn_videos_df = pd.DataFrame(cnn_videos)
fox_videos_df = pd.DataFrame(fox_videos)

cnn_comments_df = pd.DataFrame(cnn_comments)
fox_comments_df = pd.DataFrame(fox_comments)

cnn_videos_df['channel_name'] = 'CNN'
fox_videos_df['channel_name'] = 'Fox News'

cnn_merged = pd.merge(cnn_videos_df, cnn_comments_df,
                      on='video_id', how='inner')
fox_merged = pd.merge(fox_videos_df, fox_comments_df,
                      on='video_id', how='inner')

master_df = pd.concat([cnn_merged, fox_merged], ignore_index=True)

print("Number of rows: ", len(master_df))
master_df.head()

Number of rows:  11152

,video_id,view_count,title,video_date,video_description,channel_name,comment_id,comment_text,comment_author_name,comment_author_channel_id,comment_date,comment_likes,comment_reply_count
0,u-E2O-aMdSY,14076,Minneapolis Mayor says ICE agents leaving 'is ...,2026-02-05T01:48:33Z,CNN's Kasie Hunt spoke with Minneapolis Mayor ...,CNN,UgyNjKdvC4Xyk8zYl5h4AaABAg,They are regrouping.,@D_fen,UC2u_Dx5Tu64IViTSY1VInzA,2026-02-05T01:52:28Z,38,1
1,u-E2O-aMdSY,14076,Minneapolis Mayor says ICE agents leaving 'is ...,2026-02-05T01:48:33Z,CNN's Kasie Hunt spoke with Minneapolis Mayor ...,CNN,UgxS4uoWMM_-Yt5vHI94AaABAg,"""If you don't call removing the 700 agents a d...",@dogrsqr,UC43hAYxNIxNfI-HUCxn7XUg,2026-02-05T02:11:20Z,23,2
2,u-E2O-aMdSY,14076,Minneapolis Mayor says ICE agents leaving 'is ...,2026-02-05T01:48:33Z,CNN's Kasie Hunt spoke with Minneapolis Mayor ...,CNN,UgyzTnAwMsoPPfcHIwJ4AaABAg,"I agree, this is not de escalation when those ...",@laurasalazar5728,UC9_RKs37YKvnZww7nbLNmEA,2026-02-05T02:23:33Z,7,0
3,u-E2O-aMdSY,14076,Minneapolis Mayor says ICE agents leaving 'is ...,2026-02-05T01:48:33Z,CNN's Kasie Hunt spoke with Minneapolis Mayor ...,CNN,UgzT2yeuJwtJMEd3-V54AaABAg,"No, they’re just flipping them out because the...",@mafa7538,UCGsM-kCOMJ3tG4WZWWBxtpA,2026-02-05T01:59:32Z,17,2
4,u-E2O-aMdSY,14076,Minneapolis Mayor says ICE agents leaving 'is ...,2026-02-05T01:48:33Z,CNN's Kasie Hunt spoke with Minneapolis Mayor ...,CNN,Ugw2yQwJsfRDoOyqO5Z4AaABAg,"Instead of four agents to a car, there will be...",@arnoldwillis7685,UCkK5iC-2xNF7oh3Vp3wRGiQ,2026-02-05T03:19:42Z,2,0

**2d (2 pt):** Write code to turn the data frame into a CSV and save it in a file called
“yt_comments.csv”.

In [72]:
master_df.to_csv("yt_comments.csv", index=False, encoding='utf-8-sig')

## Q3 (40 pts): BlueSky data collection

**3a (15 pts)** For each of the two BlueSky accounts (The Washington Post and the New York
Times), use the BlueSky API to fetch all posts posted by each account. Check whether the post
text contains any of the topic-related keywords selected in Q1. Save relevant information about
posts related to your topic. If you are unable to identify at least 50 posts per account, expand
your list of keywords.

In [73]:
!pip install atproto --quiet

In [74]:
import json

from atproto import Client, models

In [75]:
USERNAME = "tvannpham.bsky.social"
APP_PASSWORD = "cdpv-5gbe-iqyl-e3ul"

In [76]:
client = Client()
client.login(USERNAME, APP_PASSWORD)

ProfileViewDetailed(did='did:plc:sdufr5ccus4jfzmz4mf2uifc', handle='tvannpham.bsky.social', associated=ProfileAssociated(activity_subscription=ProfileAssociatedActivitySubscription(allow_subscriptions='followers', py_type='app.bsky.actor.defs#profileAssociatedActivitySubscription'), chat=None, feedgens=0, labeler=False, lists=0, starter_packs=0, py_type='app.bsky.actor.defs#profileAssociated'), avatar='https://cdn.bsky.app/img/avatar/plain/did:plc:sdufr5ccus4jfzmz4mf2uifc/bafkreicyp33ubaevzvxkegzzddmjchhanxrr237xo7yzfy5ps7f2ra5oq4@jpeg', banner=None, created_at='2026-01-13T23:02:23.124Z', debug=None, description="UW MSIM '27 - AI & Data Science", display_name='Van Pham', followers_count=6, follows_count=21, indexed_at='2026-01-14T01:24:23.726Z', joined_via_starter_pack=None, labels=[], pinned_post=None, posts_count=3, pronouns=None, status=None, verification=None, viewer=ViewerState(activity_subscription=None, blocked_by=False, blocking=None, blocking_by_list=None, followed_by=None, following=None, known_followers=KnownFollowers(count=3, followers=[ProfileViewBasic(did='did:plc:x4ggqnuibqdvwdnjr6glfroz', handle='msaveski.bsky.social', associated=ProfileAssociated(activity_subscription=ProfileAssociatedActivitySubscription(allow_subscriptions='followers', py_type='app.bsky.actor.defs#profileAssociatedActivitySubscription'), chat=ProfileAssociatedChat(allow_incoming='following', py_type='app.bsky.actor.defs#profileAssociatedChat'), feedgens=None, labeler=None, lists=None, starter_packs=None, py_type='app.bsky.actor.defs#profileAssociated'), avatar='https://cdn.bsky.app/img/avatar/plain/did:plc:x4ggqnuibqdvwdnjr6glfroz/bafkreihwnwi4zs7kc6dk5mwgjqp4mlgwkjit2ofg3pzbn6l3bqmujjv2he@jpeg', created_at='2023-07-25T12:55:41.281Z', debug=None, display_name='Martin Saveski', labels=[], pronouns=None, status=None, verification=None, viewer=ViewerState(activity_subscription=None, blocked_by=False, blocking=None, blocking_by_list=None, followed_by='at://did:plc:x4ggqnuibqdvwdnjr6glfroz/app.bsky.graph.follow/3mcdylkvarn2v', following='at://did:plc:sdufr5ccus4jfzmz4mf2uifc/app.bsky.graph.follow/3mcdomqe6vw2b', known_followers=None, muted=False, muted_by_list=None, py_type='app.bsky.actor.defs#viewerState'), py_type='app.bsky.actor.defs#profileViewBasic'), ProfileViewBasic(did='did:plc:rhine2d32at4tqqk5tvt4rtb', handle='ischool.uw.edu', associated=ProfileAssociated(activity_subscription=ProfileAssociatedActivitySubscription(allow_subscriptions='followers', py_type='app.bsky.actor.defs#profileAssociatedActivitySubscription'), chat=None, feedgens=None, labeler=None, lists=None, starter_packs=None, py_type='app.bsky.actor.defs#profileAssociated'), avatar='https://cdn.bsky.app/img/avatar/plain/did:plc:rhine2d32at4tqqk5tvt4rtb/bafkreigf3d43uft2evnoe3lvzgculbophgqwy3qc6lw2al2lfcv6nishha@jpeg', created_at='2023-08-07T18:35:35.501Z', debug=None, display_name='University of Washington Information School', labels=[], pronouns=None, status=None, verification=None, viewer=ViewerState(activity_subscription=None, blocked_by=False, blocking=None, blocking_by_list=None, followed_by='at://did:plc:rhine2d32at4tqqk5tvt4rtb/app.bsky.graph.follow/3mdvi346sr626', following='at://did:plc:sdufr5ccus4jfzmz4mf2uifc/app.bsky.graph.follow/3mdmj5nirmd2x', known_followers=None, muted=False, muted_by_list=None, py_type='app.bsky.actor.defs#viewerState'), py_type='app.bsky.actor.defs#profileViewBasic'), ProfileViewBasic(did='did:plc:lmc4xbbyqqyui7m6ptolv3lb', handle='tkieu137.bsky.social', associated=ProfileAssociated(activity_subscription=ProfileAssociatedActivitySubscription(allow_subscriptions='followers', py_type='app.bsky.actor.defs#profileAssociatedActivitySubscription'), chat=None, feedgens=None, labeler=None, lists=None, starter_packs=None, py_type='app.bsky.actor.defs#profileAssociated'), avatar='https://cdn.bsky.app/img/avatar/plain/did:plc:lmc4xbbyqqyui7m6ptolv3lb/bafkreig5n2ooeo3ixz4yfygzcuablb4ovfm7fijbq7dorzbsfu2ezxrefy@jpeg', created_at='2026-01-13T22:59:12.525Z', debug=None, display_name='', labels=[], pronouns=None, status=None, verification=None, viewer=ViewerState(activity_subscription=None, blocked_by=False, blocking=None, blocking_by_list=None, followed_by='at://did:plc:lmc4xbbyqqyui7m6ptolv3lb/app.bsky.graph.follow/3mdhiuzn6k22e', following='at://did:plc:sdufr5ccus4jfzmz4mf2uifc/app.bsky.graph.follow/3mdmj7e6cge2j', known_followers=None, muted=False, muted_by_list=None, py_type='app.bsky.actor.defs#viewerState'), py_type='app.bsky.actor.defs#profileViewBasic')], py_type='app.bsky.actor.defs#knownFollowers'), muted=False, muted_by_list=None, py_type='app.bsky.actor.defs#viewerState'), website=None, py_type='app.bsky.actor.defs#profileViewDetailed')

In [77]:
def getBSkyPosts(client, actor_handle, count=50):
    relevant_posts = []
    cursor = None

    while True:
        response = client.get_author_feed(actor=actor_handle, cursor=cursor, limit=100)
        for feed_view in response.feed:
            post = feed_view.post
            text = post.record.text
            
            if checkKeywords(text):
                post_data = {
                    "main_post_uri": post.uri,
                    "main_poster": post.author.handle,
                    "post_created_at": post.record.created_at,
                    "post_text": text,
                    "post_like_count": post.like_count,
                    "post_reply_count": post.reply_count,
                    "post_repost_count": post.repost_count
                }
                relevant_posts.append(post_data)
        
        cursor = response.cursor
        if not cursor:
            break 

    return relevant_posts

In [78]:
wp_posts = getBSkyPosts(client, "washingtonpost.com")
len(wp_posts)

98

In [79]:
nyt_posts = getBSkyPosts(client, "nytimes.com")
len(nyt_posts)

127

In [80]:
wp_posts[0]

{'main_post_uri': 'at://did:plc:k5nskatzhyxersjilvtnz4lh/app.bsky.feed.post/3mdzyb2d5rk2n',
 'main_poster': 'washingtonpost.com',
 'post_created_at': '2026-02-04T13:30:08.376303946Z',
 'post_text': 'An Oregon judge temporarily banned federal agents from using tear gas at protests outside the ICE office in Portland, days after agents deployed the chemical agents during a largely peaceful demonstration in the city that included children.',
 'post_like_count': 121,
 'post_reply_count': 7,
 'post_repost_count': 41}

**3b (15 pts)**: For each topic-related post, collect all replies, including replies to replies (i.e., the
complete conversation thread). Make sure that you collect at least 1000 replies per account
across all posts.

In [81]:
def getReplies(client, posts_list):
    replies_info = []

    for i, main_post in enumerate(posts_list):
        main_uri = main_post['main_post_uri']
        response = client.get_post_thread(uri=main_uri)
        reply_queue = response.thread.replies

        while reply_queue:
            current_reply = reply_queue.pop()

            post = current_reply.post
            current_reply_info = {
                "main_post_uri": main_uri, # Helpful to track which topic this belongs to
                "parent_reply_URI": post.record.reply.parent.uri,
                "current_reply_URI": post.uri,
                "reply_poster": post.author.handle,
                "reply_created_at": post.record.created_at,
                "reply_text": post.record.text,
                "reply_like_count": post.like_count,
                "reply_reply_count": post.reply_count,
                "reply_repost_count": post.repost_count
            }        
            replies_info.append(current_reply_info)
            
            # Check if there are still nested reply
            if current_reply.replies:
                for child in current_reply.replies:
                    reply_queue.append(child)

    return replies_info

In [82]:
wp_replies = getReplies(client, wp_posts)

In [83]:
nyt_replies = getReplies(client, nyt_posts)

In [84]:
len(wp_replies)

3120

In [85]:
len(nyt_replies)

7458

**3c (8 pts)**: Create a Pandas data frame that contains the relevant information about the data
you extracted. Each row of your data frame should represent one reply. It should, at least,
include the following columns (you can name the columns as you like):

1. Account name (Washington Post /
New York Times)
2. Post id
3. Post text
4. Post creation time
5. Post number of likes
6. Post number of reposts
7. Reply id
8. Reply text
9. Reply creation time
10. Reply number of likes
11. Reply number of reposts

Include any additional information you think may be useful.
Print the number of rows in the data frame and display the first few rows of the data frame using
head().

In [86]:
def createMasterDf(posts_list, replies_list, account_name):
    df_posts = pd.DataFrame(posts_list)
    df_replies = pd.DataFrame(replies_list)

    merged_df = pd.merge(df_posts, df_replies, on='main_post_uri', how='inner')

    return merged_df

In [87]:
wp_df = createMasterDf(wp_posts, wp_replies, "WP")
nyt_df = createMasterDf(nyt_posts, nyt_replies, "NYT")

In [88]:
master_bsky_df = pd.concat([wp_df, nyt_df], ignore_index=True)

print("Number of rows: ", len(master_bsky_df))

master_bsky_df.head()

Number of rows:  10578

,main_post_uri,main_poster,post_created_at,post_text,post_like_count,post_reply_count,post_repost_count,parent_reply_URI,current_reply_URI,reply_poster,reply_created_at,reply_text,reply_like_count,reply_reply_count,reply_repost_count
0,at://did:plc:k5nskatzhyxersjilvtnz4lh/app.bsky...,washingtonpost.com,2026-02-04T13:30:08.376303946Z,An Oregon judge temporarily banned federal age...,121,7,41,at://did:plc:k5nskatzhyxersjilvtnz4lh/app.bsky...,at://did:plc:edvur2bbjrsmfn6jmpkyoy3x/app.bsky...,el-gran-rosamondo.bsky.social,2026-02-04T16:34:28.086Z,And unless that Judge has their own paramilita...,0,0,0
1,at://did:plc:k5nskatzhyxersjilvtnz4lh/app.bsky...,washingtonpost.com,2026-02-04T13:30:08.376303946Z,An Oregon judge temporarily banned federal age...,121,7,41,at://did:plc:k5nskatzhyxersjilvtnz4lh/app.bsky...,at://did:plc:ivfsuhienuamw6k6wvrgvaoe/app.bsky...,dumox.bsky.social,2026-02-04T14:29:38.204Z,Bezos supports fascism,0,0,0
2,at://did:plc:k5nskatzhyxersjilvtnz4lh/app.bsky...,washingtonpost.com,2026-02-04T13:30:08.376303946Z,An Oregon judge temporarily banned federal age...,121,7,41,at://did:plc:k5nskatzhyxersjilvtnz4lh/app.bsky...,at://did:plc:je6iw2v6se2yp3bituaeglgq/app.bsky...,hudsonrivercroc.bsky.social,2026-02-04T13:31:59.503Z,"lol, like ICE follows judicial orders",1,0,0
3,at://did:plc:k5nskatzhyxersjilvtnz4lh/app.bsky...,washingtonpost.com,2026-02-04T13:30:08.376303946Z,An Oregon judge temporarily banned federal age...,121,7,41,at://did:plc:k5nskatzhyxersjilvtnz4lh/app.bsky...,at://did:plc:spwrm5gruwav3nexps3ly4ky/app.bsky...,deanbooth.bsky.social,2026-02-04T13:40:18.907Z,"""How many divisions does the judge have?""",0,0,0
4,at://did:plc:k5nskatzhyxersjilvtnz4lh/app.bsky...,washingtonpost.com,2026-02-04T13:30:08.376303946Z,An Oregon judge temporarily banned federal age...,121,7,41,at://did:plc:k5nskatzhyxersjilvtnz4lh/app.bsky...,at://did:plc:t4xfo22siaxvkmgz5vdn2nk7/app.bsky...,zfrazier.bsky.social,2026-02-04T13:53:40.618Z,Can we take their guns away too?,0,0,0

**3d (2 pt)**: Write code to turn the data frame into a CSV and save it in a file called
“bsky_replies.csv”

In [89]:
master_bsky_df.to_csv("bsky_replies.csv", index=False, encoding='utf-8-sig')